// <auto-generated />
using System;
using Mesfel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mesfel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mesfel.Models.Ihale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IhaleAdi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("IhaleBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IhaleBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IhaleDurumu")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Aktif");

                    b.Property<string>("IhaleKurumu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IhaleLinki")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IhaleNumarasi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IhaleTuru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IhaleUsulu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IletisimBilgileri")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KaydedenKullanici")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("KesifBedeli")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TeklifSonTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("YaklasikMaliyet")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Ihaleler");
                });

            modelBuilder.Entity("Mesfel.Models.IhaleAnaliz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("AnalizTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("AnalizTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("EnDusukTeklif")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EnYuksekTeklif")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IhaleId")
                        .HasColumnType("int");

                    b.Property<decimal?>("KazananTeklif")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrtalamaTeklif")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Puan")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("RekabetOrani")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RekabetSeviyesi")
                        .HasColumnType("int");

                    b.Property<string>("Sonuc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("StandartSapma")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TahminEdilenKazananTeklif")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TasarrufOrani")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ToplamTeklifSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IhaleId");

                    b.ToTable("IhaleAnalizleri");
                });

            modelBuilder.Entity("Mesfel.Models.IhaleDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IhaleId")
                        .HasColumnType("int");

                    b.Property<string>("KalemAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IhaleId");

                    b.ToTable("IhaleDetaylari");
                });

            modelBuilder.Entity("Mesfel.Models.IhaleKalemi", b =>
                {
                    b.Property<int>("IhaleKalemiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IhaleKalemiId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IhaleId")
                        .HasColumnType("int");

                    b.Property<string>("KalemAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IhaleKalemiId");

                    b.HasIndex("IhaleId");

                    b.ToTable("IhaleKalemleri");
                });

            modelBuilder.Entity("Mesfel.Models.IhaleKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnaKategori")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("IhaleId")
                        .HasColumnType("int");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("IhaleId");

                    b.HasIndex("KategoriId");

                    b.ToTable("IhaleKategorileri");
                });

            modelBuilder.Entity("Mesfel.Models.IhaleTeklif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("GecerliTeklif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("IhaleAnalizId")
                        .HasColumnType("int");

                    b.Property<int>("IhaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("KdvTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TeklifDurumu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("VERILDI");

                    b.Property<DateTime>("TeklifTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("TeklifTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("IhaleAnalizId");

                    b.HasIndex("IhaleId");

                    b.ToTable("IhaleTeklifleri");
                });

            modelBuilder.Entity("Mesfel.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "İnşaat ihaleleri",
                            AktifMi = true,
                            KategoriAdi = "İnşaat",
                            KayitTarihi = new DateTime(2025, 7, 10, 1, 9, 54, 521, DateTimeKind.Local).AddTicks(5674)
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Bilgi işlem ihaleleri",
                            AktifMi = true,
                            KategoriAdi = "Bilgi İşlem",
                            KayitTarihi = new DateTime(2025, 7, 10, 1, 9, 54, 521, DateTimeKind.Local).AddTicks(6164)
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Hizmet ihaleleri",
                            AktifMi = true,
                            KategoriAdi = "Hizmet",
                            KayitTarihi = new DateTime(2025, 7, 10, 1, 9, 54, 521, DateTimeKind.Local).AddTicks(6166)
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Mal alım ihaleleri",
                            AktifMi = true,
                            KategoriAdi = "Mal",
                            KayitTarihi = new DateTime(2025, 7, 10, 1, 9, 54, 521, DateTimeKind.Local).AddTicks(6168)
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Danışmanlık hizmet ihaleleri",
                            AktifMi = true,
                            KategoriAdi = "Danışmanlık",
                            KayitTarihi = new DateTime(2025, 7, 10, 1, 9, 54, 521, DateTimeKind.Local).AddTicks(6170)
                        });
                });

            modelBuilder.Entity("Mesfel.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Kullanici");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Sistem Yöneticisi",
                            AktifMi = true,
                            Email = "admin@mesfel.com",
                            KayitTarihi = new DateTime(2025, 7, 10, 1, 9, 54, 522, DateTimeKind.Local).AddTicks(9535),
                            KullaniciAdi = "admin",
                            Rol = "Admin",
                            SifreHash = "YOUR_HASHED_PASSWORD_HERE",
                            Telefon = "555-0000"
                        });
                });

            modelBuilder.Entity("Mesfel.Models.IhaleAnaliz", b =>
                {
                    b.HasOne("Mesfel.Models.Ihale", "Ihale")
                        .WithMany("IhaleAnalizleri")
                        .HasForeignKey("IhaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ihale");
                });

            modelBuilder.Entity("Mesfel.Models.IhaleDetay", b =>
                {
                    b.HasOne("Mesfel.Models.Ihale", "Ihale")
                        .WithMany("IhaleDetaylari")
                        .HasForeignKey("IhaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ihale");
                });

            modelBuilder.Entity("Mesfel.Models.IhaleKalemi", b =>
                {
                    b.HasOne("Mesfel.Models.Ihale", "Ihale")
                        .WithMany("IhaleKalemleri")
                        .HasForeignKey("IhaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ihale");
                });

            modelBuilder.Entity("Mesfel.Models.IhaleKategori", b =>
                {
                    b.HasOne("Mesfel.Models.Ihale", "Ihale")
                        .WithMany("IhaleKategorileri")
                        .HasForeignKey("IhaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mesfel.Models.Kategori", "Kategori")
                        .WithMany("IhaleKategorileri")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ihale");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Mesfel.Models.IhaleTeklif", b =>
                {
                    b.HasOne("Mesfel.Models.IhaleAnaliz", null)
                        .WithMany("IhaleTeklifler")
                        .HasForeignKey("IhaleAnalizId");

                    b.HasOne("Mesfel.Models.Ihale", "Ihale")
                        .WithMany("IhaleTeklifleri")
                        .HasForeignKey("IhaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ihale");
                });

            modelBuilder.Entity("Mesfel.Models.Ihale", b =>
                {
                    b.Navigation("IhaleAnalizleri");

                    b.Navigation("IhaleDetaylari");

                    b.Navigation("IhaleKalemleri");

                    b.Navigation("IhaleKategorileri");

                    b.Navigation("IhaleTeklifleri");
                });

            modelBuilder.Entity("Mesfel.Models.IhaleAnaliz", b =>
                {
                    b.Navigation("IhaleTeklifler");
                });

            modelBuilder.Entity("Mesfel.Models.Kategori", b =>
                {
                    b.Navigation("IhaleKategorileri");
                });
#pragma warning restore 612, 618
        }
    }
}
